"""Export generated microstructures as RVEs for FEM / FFT homogenization codes (VTI, MetaImage, Abaqus, NumPy, TIFF).

Volumes larger than the 64^3 training size are generated by enlarging the latent input (output edge
= 32 * latent_size - 64), as described in the SliceGAN paper. Periodic RVEs use SliceGAN's latent-tiling
trick (the first two latent slices copied from the last two along each periodic axis); the generated field
then repeats with period N - 2 voxels, so 2 voxels are cropped per periodic axis (measured: the wrap-around
mismatch matches the mismatch between neighbouring interior slices). Labels: 0 = matrix, 1 = inclusion.
"""

from __future__ import annotations

import argparse
import base64
import json
import struct
from pathlib import Path

import numpy as np
import tifffile
import torch
import yaml

from src.models.generate import load_generator
from src.models.slicegan_wrapper import to_labels
from src.tracking import git_commit
from src.utils import get_device, get_logger, load_config, setup_logging

log = get_logger(__name__)

FORMATS = ("vti", "mhd", "inp", "npy", "tif")
PHASES = {0: "matrix", 1: "inclusion"}
PERIODIC_CROP = 2  # period of the tiled-latent field is N - 2 voxels (see module docstring)


# ----------------------------------------------------------------------------- generation


def latent_size_for(size: int) -> int:
    """Latent spatial size giving an output edge of `size` (= 32 * lz - 64; 64, 96, 128, ...)."""
    if size < 64 or (size - 64) % 32:
        raise ValueError(f"RVE size must be 64 + 32k voxels (64, 96, 128, ...), got {size}")
    return (size + 64) // 32


@torch.no_grad()
def generate_rve(netG, size: int, seed: int, z_channels: int, device, periodic: bool) -> np.ndarray:
    """One label volume (Z, Y, X); periodic volumes are (size - 2)^3 and tile seamlessly."""
    if hasattr(netG, "sample_volume"):  # M6 diffusion: fixed 64^3, non-periodic
        if periodic or size != netG.size:
            raise ValueError(f"The diffusion model (M6) generates non-periodic {netG.size}^3 volumes only")
        return netG.sample_volume(seed)
    lz = latent_size_for(size)
    gen = torch.Generator(device=device).manual_seed(int(seed))
    z = torch.randn(1, z_channels, lz, lz, lz, device=device, generator=gen)
    if periodic:
        z[:, :, :2] = z[:, :, -2:]
        z[:, :, :, :2] = z[:, :, :, -2:]
        z[:, :, :, :, :2] = z[:, :, :, :, -2:]
    vol = to_labels(netG(z))[0]
    if periodic:
        c = PERIODIC_CROP
        vol = vol[:-c, :-c, :-c]
    return np.ascontiguousarray(vol)


def seam_quality(vol: np.ndarray) -> dict[str, float]:
    """Per axis: mismatch of the wrap-around face pair vs the mean mismatch of neighbouring interior slices.

    A ratio near 1 means the volume continues across its boundary as smoothly as inside (periodic);
    non-periodic volumes give ratios around 10.
    """
    out = {}
    for axis, name in enumerate("zyx"):
        v = np.moveaxis(vol, axis, 0)
        interior = float(np.mean(v[1:] != v[:-1]))
        wrap = float(np.mean(v[-1] != v[0]))
        out[f"seam_ratio_{name}"] = wrap / interior if interior > 0 else float("nan")
    return out


# ----------------------------------------------------------------------------- writers


def write_vti(vol: np.ndarray, path: Path, spacing: float) -> None:
    """VTK XML ImageData, one cell per voxel, int32 cell array `material` (base64, ParaView / DAMASK style)."""
    nz, ny, nx = vol.shape
    data = vol.astype("<i4").tobytes(order="C")  # x fastest, as VTK expects for (z, y, x) C-order
    payload = base64.b64encode(struct.pack("<I", len(data)) + data).decode("ascii")
    path.write_text(
        '<?xml version="1.0"?>\n'
        '<VTKFile type="ImageData" version="1.0" byte_order="LittleEndian" header_type="UInt32">\n'
        f'  <ImageData WholeExtent="0 {nx} 0 {ny} 0 {nz}" Origin="0 0 0" Spacing="{spacing} {spacing} {spacing}">\n'
        f'    <Piece Extent="0 {nx} 0 {ny} 0 {nz}">\n'
        '      <CellData Scalars="material">\n'
        f'        <DataArray type="Int32" Name="material" format="binary">{payload}</DataArray>\n'
        '      </CellData>\n'
        '    </Piece>\n'
        '  </ImageData>\n'
        '</VTKFile>\n',
        encoding="ascii",
    )


def write_mhd(vol: np.ndarray, path: Path, spacing: float) -> None:
    """MetaImage header + raw uint8 voxels (ITK, ParaView, FFT homogenization solvers)."""
    raw = path.with_suffix(".raw")
    vol.astype(np.uint8).tofile(raw)
    nz, ny, nx = vol.shape
    path.write_text(
        "ObjectType = Image\nNDims = 3\nBinaryData = True\nBinaryDataByteOrderMSB = False\n"
        f"DimSize = {nx} {ny} {nz}\nElementSpacing = {spacing} {spacing} {spacing}\n"
        f"ElementType = MET_UCHAR\nElementDataFile = {raw.name}\n",
        encoding="ascii",
    )


def write_abaqus_inp(vol: np.ndarray, path: Path, spacing: float, name: str) -> dict[str, int]:
    """Hexahedral voxel mesh (C3D8): one element set per phase and node sets on the six faces (for PBCs)."""
    nz, ny, nx = vol.shape
    node_id = lambda i, j, k: 1 + i + (nx + 1) * (j + (ny + 1) * k)  # noqa: E731
    k, j, i = np.meshgrid(np.arange(nz), np.arange(ny), np.arange(nx), indexing="ij")
    i, j, k = i.ravel(), j.ravel(), k.ravel()
    conn = np.stack([node_id(i, j, k), node_id(i + 1, j, k), node_id(i + 1, j + 1, k), node_id(i, j + 1, k),
                     node_id(i, j, k + 1), node_id(i + 1, j, k + 1), node_id(i + 1, j + 1, k + 1),
                     node_id(i, j + 1, k + 1)], axis=1)
    elem_ids = np.arange(1, conn.shape[0] + 1)
    labels = vol.ravel()  # same (z, y, x) C-order as the element loop above

    nodes_i = np.arange((nx + 1) * (ny + 1) * (nz + 1))
    ni = nodes_i % (nx + 1)
    nj = (nodes_i // (nx + 1)) % (ny + 1)
    nk = nodes_i // ((nx + 1) * (ny + 1))
    coords = np.stack([ni, nj, nk], axis=1) * spacing

    def id_block(ids: np.ndarray) -> str:
        lines = [", ".join(map(str, ids[s : s + 16])) for s in range(0, len(ids), 16)]
        return "\n".join(lines) + "\n"

    with path.open("w", encoding="ascii") as fh:
        fh.write(f"*Heading\n** RVE {name}: {nx}x{ny}x{nz} voxels, voxel size {spacing} (length unit of the source)\n")
        fh.write("** Generated by src/models/export_rve.py; phases: 0 = matrix (ELSET MATRIX), 1 = inclusion "
                 "(ELSET INCLUSION). Assign materials to the two sections.\n")
        fh.write("*Node\n")
        np.savetxt(fh, np.column_stack([nodes_i + 1, coords]), fmt=["%d", "%.6g", "%.6g", "%.6g"], delimiter=", ")
        fh.write("*Element, type=C3D8\n")
        np.savetxt(fh, np.column_stack([elem_ids, conn]), fmt="%d", delimiter=", ")
        counts = {}
        for lab, phase in PHASES.items():
            ids = elem_ids[labels == lab]
            counts[phase] = int(len(ids))
            if len(ids):
                fh.write(f"*Elset, elset={phase.upper()}\n" + id_block(ids))
        for face, mask in (("XMIN", ni == 0), ("XMAX", ni == nx), ("YMIN", nj == 0), ("YMAX", nj == ny),
                           ("ZMIN", nk == 0), ("ZMAX", nk == nz)):
            fh.write(f"*Nset, nset={face}\n" + id_block(nodes_i[mask] + 1))
        for phase in PHASES.values():
            if counts[phase]:
                fh.write(f"*Solid Section, elset={phase.upper()}, material=MAT_{phase.upper()}\n,\n")
    return counts


def write_rve(vol: np.ndarray, out_dir: Path, stem: str, formats: list[str], spacing: float) -> list[str]:
    """Write one RVE in every requested format; returns the file names written."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for fmt in formats:
        path = out_dir / f"{stem}.{fmt}"
        try:
            if fmt == "vti":
                write_vti(vol, path, spacing)
            elif fmt == "mhd":
                write_mhd(vol, path, spacing)
                written.append(path.with_suffix(".raw").name)
            elif fmt == "inp":
                write_abaqus_inp(vol, path, spacing, stem)
            elif fmt == "npy":
                np.save(path, vol.astype(np.uint8))
            elif fmt == "tif":
                tifffile.imwrite(path, vol.astype(np.uint8) * 255)
            else:
                raise ValueError(f"Unknown format '{fmt}' (expected one of {FORMATS})")
        except OSError as exc:
            log.error("Could not write %s: %s", path, exc)
            continue
        written.append(path.name)
    return written


# ----------------------------------------------------------------------------- CLI


def main() -> None:
    """CLI: export RVEs from a trained model."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", required=True)
    parser.add_argument("--data", action="append", default=[], help="dataset overlay yaml")
    parser.add_argument("--seeds", type=int, nargs="+", default=[0])
    parser.add_argument("--size", type=int, default=128, help="generated edge before periodic crop: 64, 96, 128, ...")
    parser.add_argument("--periodic", action="store_true", help="periodic RVE (edge = size - 2)")
    parser.add_argument("--formats", nargs="+", default=["vti", "mhd", "npy"], choices=FORMATS)
    parser.add_argument("--checkpoint", default=None, help="G checkpoint file; default: the one chosen by generate")
    parser.add_argument("--out", default="exports")
    parser.add_argument("--device", default=None)
    args = parser.parse_args()

    cfg = load_config(args.config, args.data)
    setup_logging(cfg["paths"]["logs"], f"export_rve_{cfg['run_name']}", cfg["logging"]["level"])
    run_dir = Path(cfg["paths"]["models"]) / cfg["run_name"]
    ckpt = args.checkpoint
    if ckpt is None:
        metrics = run_dir / "metrics.yaml"
        ckpt = (yaml.safe_load(metrics.read_text(encoding="utf-8")).get("checkpoint") if metrics.exists()
                else None) or "G_best.pt"
    device = get_device(args.device or cfg["device"])
    netG = load_generator(cfg, run_dir, device, checkpoint=ckpt)
    spacing = float((cfg["data"].get("microlib") or {}).get("pixel_size_um") or 1.0)
    unit = "um" if (cfg["data"].get("microlib") or {}).get("pixel_size_um") else "voxel"
    out_dir = Path(args.out) / cfg["data"]["name"] / cfg["run_name"]

    for seed in args.seeds:
        vol = generate_rve(netG, args.size, seed, cfg["z_channels"], device, args.periodic)
        stem = f"rve_{vol.shape[0]}{'p' if args.periodic else ''}_seed{seed}"
        files = write_rve(vol, out_dir, stem, args.formats, spacing)
        meta = {
            "model": cfg["run_name"], "dataset": cfg["data"]["name"], "checkpoint": ckpt, "seed": seed,
            "shape_zyx": list(vol.shape), "periodic": args.periodic, "voxel_size": spacing, "length_unit": unit,
            "physical_size": [round(n * spacing, 6) for n in vol.shape], "phases": PHASES,
            "phase_fractions": {PHASES[k]: float(np.mean(vol == k)) for k in PHASES},
            **seam_quality(vol), "files": files, "git_commit": git_commit(),
        }
        (out_dir / f"{stem}.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
        log.info("%s: %s, phi=%.4f, seam ratios z/y/x %.2f/%.2f/%.2f -> %s", stem, vol.shape,
                 meta["phase_fractions"]["inclusion"], meta["seam_ratio_z"], meta["seam_ratio_y"],
                 meta["seam_ratio_x"], out_dir)


if __name__ == "__main__":
    main()
